certmanager:
  enabled: true
  issuer:
    # Set this to your company email.
    email: fazelshah1@gmail.com
    # Set this to true once staging certificates are issued successfully.
    # Otherwise you may run into rate-limiting issues.
    production: true
ingress:
  enabled: true

  ingressClassName: nginx

  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

  hosts:
    - grafana.fazelshah.fun
  tls:
    - secretName: grafana-tls

  path: /
  pathType: Prefix
