certmanager:
  enabled: true
  issuer:
    email: fazelshah1@gmail.com
    production: true

ingress:
  enabled: true
  ingressClassName: alb

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    cert-manager.io/cluster-issuer: letsencrypt-prod
    #kubernetes.io/ingress.class: nginx
    #cert-manager.io/cluster-issuer: letsencrypt-prod
    #nginx.ingress.kubernetes.io/ssl-redirect: "true"

  hosts:
    - grafana.fazelshah.fun

  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.fazelshah.fun

  path: /
  pathType: Prefix
