certmanager:
  enabled: true
  issuer:
    email: fazelshah1@gmail.com
    production: true

ingress:
  enabled: true
  ingressClassName: nginx

  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

  hosts:
    - grafana.fazelshah.fun

  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.fazelshah.fun

  path: /
  pathType: Prefix
