# This section enables Ingress for the *application* deployment
ingress:
  enabled: true
  className: "nginx" # Use the specific class name of your controller
  hostname: devlake.example.com
  # The chart's template uses this to define the actual rules
  annotations:
    kubernetes.io/ingress.class: nginx 

# Ensure the UI service port is set correctly (4000 by default)
service:
  type: NodePort # or ClusterIP, this defines the internal service
  uiPort: 32001 # NodePort value, the Ingress uses the internal port
