certmanager:
  enabled: true
  issuer:
    # Set this to your company email.
    email: fazelshah1@gmail.com
    # Set this to true once staging certificates are issued successfully.
    # Otherwise you may run into rate-limiting issues.
    production: true
ingress:
  enabled: true

  ingressClassName: nginx

  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: nginx

  hosts:
    - devlake.example.com

  path: /
  pathType: ImplementationSpecific
