ingress:
  enabled: true
  className: "nginx"
  hostname: devlake.example.com
  # Use ImplementationSpecific to allow regex characters in paths
  pathType: ImplementationSpecific 
  annotations:
    kubernetes.io/ingress.class: nginx
    # Required if your path uses regex like (.*)
    nginx.ingress.kubernetes.io/use-regex: "true" 
    # Often used with DevLake to handle path rewrites
    nginx.ingress.kubernetes.io/rewrite-target: /$2 

service:
  type: NodePort
  uiPort: 32001
