ingress:
  enabled: true
  className: "nginx"
  hostname: devlake.example.com
  # This setting must propagate to the 'pathType' field in the generated Ingress YAML
  pathType: ImplementationSpecific 
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
