ingress:
  enabled: true
  ingressClassName: nlb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  hosts:
    - host: dora.test.com
      paths:
        - path: /
          pathType: Prefix