certmanager:
  enabled: true
  issuer:
    name: letsencrypt-prod
    kind: ClusterIssuer

ingress:
  enabled: true
  enableHttps: true
  hostname: devlake-0.fazelshah.fun
  className: nginx
  httpsPort: 8443
  tlsSecretName: ssl-certificate
  pathType: ImplementationSpecific
