name: ingress-deployment

on:
  workflow_dispatch:
    inputs:
      eksClusterName:
        description: "EKS Cluster Name"
        required: true
        type: choice
        options:
        - k8-cluster
      awsRegion: 
        description: "AWS Region"
        required: true
        type: choice
        options:
        - ap-south-1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_EKS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_EKS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Kubeconfig for Amazon EKS Cluster
        run: aws eks update-kubeconfig --name ${{ github.event.inputs.eksClusterName }} --region ap-south-1

     

      - name: Deploy issuer
        run: |
          kubectl apply -f issuer.yaml
