name: Delete EKS  Cluster

on:
  workflow_dispatch: {}   

env:
  EKS_CLUSTER_NAME: cryptlex-grafana-apm-eks-cluster-v34
  AWS_REGION: ap-south-1

jobs:
  delete:
    name: Delete EKS Cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_EKS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_EKS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C ./
          chmod +x eksctl

      - name: Delete EKS cluster
        run: ./eksctl delete cluster --name "${EKS_CLUSTER_NAME}" --region ap-south-1